### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by davethiede**
This PR:
1. updates the rust version to 2023-07-11
2. removes Cargo.lock from .dockerignore
3. removes obsolete (as of 2023-07-11) feature flags
4. removes a type ascription that is no longer supported by Rust
5. updates Cargo.lock
6. greatly simplifies the Dockerfile removing all redundancies and now depends on rust-toolchain.toml for component, target and channel information.

Features of this PR were inspired by the work of xonmello and earney and replaces https://github.com/LibertyOS-Development/kernel/pull/22

### CODE REVIEW

**Comment by danielteberian** [comment]
I just pushed a new version to the repository. I think I did a few of the things you did, but I am not sure. Can I merge the request?

**Comment by davethiede** [comment]
you should be able to merge it. the feature flags patch should be redundant now. the rust-toolchain.toml file would create a conflict as I'm using the nightly-2023-07-11 version in my PR.

I don't know why patch e49ec3a showed up here. i was experimenting with bootimage on my forked repo.

**Comment by danielteberian** [comment]
Why did you close it?

**Comment by danielteberian** [comment]
Are you going to create a PR with the changes that still need to be made? I want to include your work. :)

**Pull request closed without merging**
